services:
  - type: web
    name: cyber-knights-quest
    env: static
    staticPublishPath: .
    buildCommand: ""
    startCommand: ""
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
